export default Object.freeze({
    UNAUTHENTICATED: 'UNAUTHENTICATED',
    INVALID_VERIFICATION_CODE: 'INVALID_VERIFICATION_CODE',
    VERIFICATION_CODE_EXPIRED: 'VERIFICATION_CODE_EXPIRED',
    RATE_LIMITED: 'RATE_LIMITED',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    ALREADY_VERIFIED: 'ALREADY_VERIFIED',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    OAUTH_ONLY_ACCOUNT: 'OAUTH_ONLY_ACCOUNT',
    OAUTH_ACCOUNT_ALREADY_REGISTERED: 'OAUTH_ACCOUNT_ALREADY_REGISTERED',
    OAUTH_ACCOUNT_NOT_REGISTERED: 'OAUTH_ACCOUNT_NOT_REGISTERED',
    OAUTH_ACCOUNT_MISMATCH: 'OAUTH_ACCOUNT_MISMATCH',
    PASSWORD_REQUIRED: 'PASSWORD_REQUIRED'
} as const)