export default Object.freeze({
    UNAUTHENTICATED: 'UNAUTHENTICATED',
    VERIFICATION_CODE_EXPIRED: 'VERIFICATION_CODE_EXPIRED',
    INVALID_VERIFICATION_CODE: 'INVALID_VERIFICATION_CODE',
    OAUTH_ONLY_ACCOUNT: 'OAUTH_ONLY_ACCOUNT',
    ALREADY_VERIFIED: 'ALREADY_VERIFIED'
} as const)